version: '3.8'

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports: 
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=dcoker
      - POSTGRESQL_DATABASE=apisolid 

